### ISSUE TITLE
Support for Node v15

### ISSUE THREAD

**Issue by tujoworker** [Prior99/native-image-diff#20]
Hi!

Thanks again for this very good lib @Prior99 💯 ❤️

Now, with Node v15 out, I get this error: 

`No supported native-image-diff 0.1.10 build found for node v15.0.1 on darwin (x64)`

Looks like you have experience to update the deps in order to add support for Node v14 – so I hope and assume, it is just a small thing - is it?

**Comment by Prior99** [comment]
I had to wait for Appveyour to support Node 15. Version 0.1.11 now supports Node 15.

**Comment by tujoworker** [comment]
Thank you 🤗 Hope you are ok in Hamburg! Nice city! I lived there for over 3 years, back in 2002-2005 💙

**Comment by Prior99** [comment]
Everythig fine here :) Thanks. I hope you and your family stays safe, too!

**Comment by tujoworker** [comment]
Bummer! Node v15 is already dead in just some days: `2021-06-01` when I check the https://nodejs.org/en/about/releases/ **End-of-life** table.

Is Appveyor ready for Node v16?
