### ISSUE TITLE
Provided image wasn't a diffable image.

### ISSUE THREAD

**Issue by kanekotic** [Prior99/native-image-diff#6]
I have 2 correct `.jpg` images and they fail to be compared due `Provided image wasn't a diffable image`. The error is caused because the function `getBytesPerPixel` returns `0,14`. Why is this check in place?

[Example of 640 by 480 failing image](https://user-images.githubusercontent.com/3071208/45629204-24cbd900-ba96-11e8-8a86-97865e0daea3.jpg)

**Comment by Prior99** [comment]
Hi, can you provide me with a minimal example?
 
Having `0.14` bytes per pixel sounds odd. 

Did you perhaps try to diff an undecoded image?
This library doesn't do the decoding itself, it operates on an array of RGB or RGBA data.

**Comment by AScripnic** [comment]
@Prior99 I found the same issue, when using `sharp` module to resize and image and the trying to compare, it just has <1 bpp

**Comment by Prior99** [comment]
This module doesn't handle image compression. Are you trying to diff an image that is encoded?

**Comment by AScripnic** [comment]
@Prior99 seems like this is the case. If you have by default an encoded image (if I'm understanding correct the terms, encoded means <3 bpp?) you'll have to somehow decode it first then compare.
If this module doesn't have the functionality to compare encoded images, it be great to have such a functionality, if not, then I believe this thread can be closed. (if @kanekotic agrees. @kanekotic I can provide how I bypassed this issue using another module to transform image to 3/4 bpp, if you need)

**Comment by Prior99** [comment]
This project doesn't do decoding, but for example [node-libpng](https://www.npmjs.com/package/node-libpng) does. Take a look at this example: https://github.com/Prior99/native-image-diff#usage-with-node-libpng
