### ISSUE TITLE
Include binary in github repo?

### ISSUE THREAD

**Issue by chrisjlee** [Prior99/native-image-diff#8]
Is it possible to add the binary in this repository to be deployed via npm?

If you have a private repository and are behind a firewall it's impossible to install this package instead of being added to package. I can update the post install script if needed.

**Comment by Prior99** [comment]
I will not check the built binaries into the repository. This is very bad practice, as it will get out of date very quickly and is a mess to maintain.

Repositories are ment for sources only.

However, after each build multiple CIs are starting and will build the binary and upload [it to the release section of the repository](https://github.com/Prior99/native-image-diff/releases).

Adding the binary to the NPM package is not a good idea as there is a binary for each combination of:

- Version of node (4, 6, 8, 10, 11, ...)
- OS (Windows, Linux, OSX)
- Architecture (x86, x86_64)

This would blow the package up extremely.

I recommend you configure NPM to work together with your corporate's firewall.

**Comment by chrisjlee** [comment]
Fair enough. Thanks for the feedback.

**Comment by Prior99** [comment]
This is already possible. The variable is
named NATIVE_IMAGE_DIFF_BINARY_URL.

**Comment by jmanj78** [comment]
Yep, found that 5 minutes after I posted the comment, so I deleted it.
